import { BaseAgentExecutor } from './base';
import { Task, TaskResult } from '../types';

export class CoderAgentExecutor extends BaseAgentExecutor {
  readonly agentId = 'coder' as const;
  readonly timeout = 60000;

  private readonly baseUrl: string;

  constructor(baseUrl = 'http://localhost:8765') {
    super();
    this.baseUrl = baseUrl;
  }

  protected async doExecute(task: Task): Promise<TaskResult> {
    const codeTask = this.detectCodeTask(task.description);

    if (codeTask.action === 'execute') {
      return this.executeCode(codeTask);
    } else if (codeTask.action === 'analyze') {
      return this.analyzeCode(codeTask);
    } else {
      return this.generateCode(codeTask);
    }
  }

  private detectCodeTask(description: string): {
    action: 'generate' | 'execute' | 'analyze';
    language: string;
    code?: string;
  } {
    const execMatch = description.match(/run|execute|run this|in python|in javascript/i);
    const analyzeMatch = description.match(/analyze|review|check|debug|fix/i);
    const langMatch = description.match(/\b(python|javascript|typescript|java|rust|go|c\+\+)\b/i);

    const language = langMatch ? langMatch[1].toLowerCase() : 'python';

    const codeBlockMatch = description.match(/```[\s\S]*?```/);

    if (execMatch && codeBlockMatch) {
      return { action: 'execute', language, code: codeBlockMatch[0] };
    }

    if (analyzeMatch) {
      return { action: 'analyze', language };
    }

    return { action: 'generate', language };
  }

  private async generateCode(task: {
    language: string;
  }): Promise<TaskResult> {
    return {
      taskId: `coder-gen-${Date.now()}`,
      agentId: this.agentId,
      success: true,
      data: {
        language: task.language,
        code: `-- Code generation for ${task.language} task
-- This would be generated by the LLM with code-specific system prompt`,
        explanation: 'Code generation task created'
      },
      confidence: 0.8,
      reasoning: 'Generated code based on task requirements',
      timestamp: Date.now()
    };
  }

  private async executeCode(task: {
    code?: string;
    language: string;
  }): Promise<TaskResult> {
    if (!task.code) {
      return {
        taskId: `coder-exec-${Date.now()}`,
        agentId: this.agentId,
        success: false,
        error: 'No code provided for execution',
        confidence: 0,
        timestamp: Date.now()
      };
    }

    try {
      const response = await fetch(`${this.baseUrl}/tool`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          tool: 'execute_code',
          params: {
            code: task.code,
            language: task.language
          }
        })
      });

      const data = await response.json();

      return {
        taskId: `coder-exec-${Date.now()}`,
        agentId: this.agentId,
        success: response.ok,
        data: {
          output: data.result || data.error || 'Code executed',
          language: task.language
        },
        confidence: response.ok ? 0.9 : 0.5,
        reasoning: 'Executed code in sandbox environment',
        timestamp: Date.now()
      };
    } catch (error) {
      return {
        taskId: `coder-exec-${Date.now()}`,
        agentId: this.agentId,
        success: false,
        error: error instanceof Error ? error.message : String(error),
        confidence: 0,
        timestamp: Date.now()
      };
    }
  }

  private async analyzeCode(task: { language: string }): Promise<TaskResult> {
    return {
      taskId: `coder-analysis-${Date.now()}`,
      agentId: this.agentId,
      success: true,
      data: {
        language: task.language,
        analysis: 'Code analysis would be performed here',
        suggestions: ['Consider adding error handling', 'Add type annotations']
      },
      confidence: 0.75,
      reasoning: 'Analyzed code structure and patterns',
      timestamp: Date.now()
    };
  }
}
